version: '3.8'

networks:
  dev:
    driver: bridge

services:
  projeto:
    image: docker.io/library/projeto_ddd
    depends_on:
      - "mssql-server"
    container_name: projeto-services
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql-server,1433;Database=PROJETO_DB;User Id=SA;Password=@Sdfl29052003;Encrypt=True;TrustServerCertificate=True
      - ASPNETCORE_URLS=http://+:80

    ports:
      - "8080:80"
    networks:
      - dev

  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "@Sdfl29052003"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sql_server_data:/var/lib/sqlserver/data
    networks:
      - dev

volumes:
  sql_server_data:
